# ==============================================================================
# HTS vs LTS classification input | Figure 1 TWAS-DEG gene sets
#
# Purpose:
#   1. Read Positive and Negative TWAS-DEG gene sets generated by Figure 1
#   2. Extract their normalized RNA expression from scRNA_harmony
#   3. Retain HTS and LTS cells according to IC_class
#   4. Encode HTS = 1 and LTS = 0
#   5. Export a cell-by-gene expression matrix for downstream classification /
#      machine-learning analysis
#
# This script is designed to use Figure 1 output DIRECTLY:
#   TWAS_DEG_gene_sets.csv
#
# Required columns in TWAS_DEG_gene_sets.csv:
#   direction : Positive / Negative
#   gene      : gene symbol
#
# Required object:
#   scRNA_harmony
#
# Required metadata:
#   IC_class
# ==============================================================================


# ==============================================================================
# 0. Packages and settings
# ==============================================================================

suppressPackageStartupMessages({
  library(Seurat)
})

FIGURE1_GENESET_FILE <- "TWAS_DEG_gene_sets.csv"
GROUP_COL <- "IC_class"
ASSAY_USE <- "RNA"
LAYER_USE <- "data"

OUTPUT_EXPRESSION_FILE <- "HTS_vs_LTS_Figure1_gene_expression.csv"
OUTPUT_GENE_INFO_FILE <- "HTS_vs_LTS_Figure1_gene_features.csv"
OUTPUT_POSITIVE_FILE <- "Figure1_TWAS_DEG_POS_matched_RNA.csv"
OUTPUT_NEGATIVE_FILE <- "Figure1_TWAS_DEG_NEG_matched_RNA.csv"
OUTPUT_MISSING_FILE <- "Figure1_TWAS_DEG_genes_missing_RNA.csv"


# ==============================================================================
# 1. Input checks
# ==============================================================================

if (!exists("scRNA_harmony")) {
  stop(
    "The Seurat object 'scRNA_harmony' is not available in the R environment."
  )
}

if (!file.exists(FIGURE1_GENESET_FILE)) {
  stop(
    "Figure 1 gene-set file not found: ",
    FIGURE1_GENESET_FILE,
    "\nRun Figure 1 first to generate TWAS_DEG_gene_sets.csv."
  )
}

if (!GROUP_COL %in% colnames(scRNA_harmony@meta.data)) {
  stop(
    "Required metadata column not found: ",
    GROUP_COL,
    "\nRun the Figure 3 HTS/MTS/LTS classification first or add IC_class to scRNA_harmony."
  )
}

if (!ASSAY_USE %in% Assays(scRNA_harmony)) {
  stop(
    "Required assay not found in scRNA_harmony: ",
    ASSAY_USE
  )
}


# ==============================================================================
# 2. Read Figure 1 Positive / Negative TWAS-DEG gene sets
# ==============================================================================

figure1_gene_sets <- read.csv(
  FIGURE1_GENESET_FILE,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

required_columns <- c(
  "direction",
  "gene"
)

missing_columns <- setdiff(
  required_columns,
  colnames(figure1_gene_sets)
)

if (length(missing_columns) > 0) {
  stop(
    "TWAS_DEG_gene_sets.csv is missing required columns: ",
    paste(
      missing_columns,
      collapse = ", "
    )
  )
}

figure1_gene_sets$direction <- trimws(
  as.character(
    figure1_gene_sets$direction
  )
)

figure1_gene_sets$gene <- trimws(
  as.character(
    figure1_gene_sets$gene
  )
)

# Keep the names exactly consistent with Figure 1.
allowed_directions <- c(
  "Positive",
  "Negative"
)

unexpected_directions <- setdiff(
  unique(
    figure1_gene_sets$direction[
      !is.na(figure1_gene_sets$direction)
    ]
  ),
  allowed_directions
)

if (length(unexpected_directions) > 0) {
  stop(
    "Unexpected direction labels in Figure 1 gene-set file: ",
    paste(
      unexpected_directions,
      collapse = ", "
    ),
    "\nExpected only: Positive and Negative."
  )
}

figure1_gene_sets <- figure1_gene_sets[
  !is.na(figure1_gene_sets$gene) &
    nzchar(figure1_gene_sets$gene) &
    figure1_gene_sets$direction %in% allowed_directions,
  ,
  drop = FALSE
]

figure1_gene_sets <- unique(
  figure1_gene_sets[
    ,
    c(
      "direction",
      "gene"
    ),
    drop = FALSE
  ]
)

genes_pos <- unique(
  figure1_gene_sets$gene[
    figure1_gene_sets$direction == "Positive"
  ]
)

genes_neg <- unique(
  figure1_gene_sets$gene[
    figure1_gene_sets$direction == "Negative"
  ]
)

cat(
  "Figure 1 TWAS-DEG positive genes:",
  length(genes_pos),
  "\n"
)

cat(
  "Figure 1 TWAS-DEG negative genes:",
  length(genes_neg),
  "\n"
)

if (length(genes_pos) == 0) {
  warning(
    "No Positive TWAS-DEG genes were found."
  )
}

if (length(genes_neg) == 0) {
  warning(
    "No Negative TWAS-DEG genes were found."
  )
}

genes_all <- unique(
  c(
    genes_pos,
    genes_neg
  )
)

if (length(genes_all) == 0) {
  stop(
    "No Figure 1 TWAS-DEG genes are available for expression extraction."
  )
}


# ==============================================================================
# 3. Extract normalized RNA expression from scRNA_harmony
# ==============================================================================

DefaultAssay(
  scRNA_harmony
) <- ASSAY_USE

expr_mat <- Seurat::GetAssayData(
  scRNA_harmony,
  assay = ASSAY_USE,
  layer = LAYER_USE
)

if (nrow(expr_mat) == 0 || ncol(expr_mat) == 0) {
  stop(
    "The RNA data layer is empty. ",
    "Run NormalizeData(scRNA_harmony) before this script."
  )
}

cat(
  "RNA expression matrix:",
  nrow(expr_mat),
  "genes x",
  ncol(expr_mat),
  "cells\n"
)


# ==============================================================================
# 4. Match Figure 1 genes to the RNA assay
# ==============================================================================

genes_pos_matched <- intersect(
  genes_pos,
  rownames(expr_mat)
)

genes_neg_matched <- intersect(
  genes_neg,
  rownames(expr_mat)
)

genes_pos_missing <- setdiff(
  genes_pos,
  rownames(expr_mat)
)

genes_neg_missing <- setdiff(
  genes_neg,
  rownames(expr_mat)
)

genes_matched <- unique(
  c(
    genes_pos_matched,
    genes_neg_matched
  )
)

if (length(genes_matched) == 0) {
  stop(
    "None of the Figure 1 TWAS-DEG genes were found in the RNA assay."
  )
}

cat(
  "Positive genes matched:",
  length(genes_pos_matched),
  "/",
  length(genes_pos),
  "\n"
)

cat(
  "Negative genes matched:",
  length(genes_neg_matched),
  "/",
  length(genes_neg),
  "\n"
)

cat(
  "Total unique gene features retained:",
  length(genes_matched),
  "\n"
)


# ==============================================================================
# 5. Keep HTS and LTS cells
# ==============================================================================

metadata <- scRNA_harmony@meta.data

cell_groups <- as.character(
  metadata[
    colnames(expr_mat),
    GROUP_COL
  ]
)

names(cell_groups) <- colnames(expr_mat)

cells_use <- names(cell_groups)[
  cell_groups %in% c(
    "HTS",
    "LTS"
  )
]

if (length(cells_use) == 0) {
  stop(
    "No HTS or LTS cells were found in scRNA_harmony$",
    GROUP_COL,
    "."
  )
}

label_vector <- ifelse(
  cell_groups[cells_use] == "HTS",
  1L,
  0L
)

cat(
  "\nHTS/LTS cell counts before matrix construction:\n"
)

print(
  table(
    factor(
      cell_groups[cells_use],
      levels = c(
        "LTS",
        "HTS"
      )
    )
  )
)


# ==============================================================================
# 6. Construct HTS vs LTS cell-by-gene expression matrix
# ==============================================================================

expression_subset <- expr_mat[
  genes_matched,
  cells_use,
  drop = FALSE
]

df_expr <- as.data.frame(
  t(
    as.matrix(
      expression_subset
    )
  ),
  check.names = FALSE
)

df_expr <- data.frame(
  label = label_vector[
    rownames(df_expr)
  ],
  IC_class = cell_groups[
    rownames(df_expr)
  ],
  cell = rownames(df_expr),
  df_expr,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

# Explicitly ensure binary labels are correct.
if (
  any(
    is.na(
      df_expr$label
    )
  )
) {
  stop(
    "NA labels were generated unexpectedly."
  )
}

if (
  !all(
    unique(
      df_expr$label
    ) %in% c(
      0L,
      1L
    )
  )
) {
  stop(
    "Labels must contain only 0 (LTS) and 1 (HTS)."
  )
}


# ==============================================================================
# 7. Feature annotation
#
# Preserve Positive / Negative direction for each feature so downstream machine
# learning results can be linked back to the Figure 1 biological direction.
# ==============================================================================

feature_info <- figure1_gene_sets[
  figure1_gene_sets$gene %in% genes_matched,
  ,
  drop = FALSE
]

feature_info <- feature_info[
  match(
    genes_matched,
    feature_info$gene
  ),
  ,
  drop = FALSE
]

rownames(
  feature_info
) <- NULL


# ==============================================================================
# 8. Quality control
# ==============================================================================

cat(
  "\nFinal binary-classification dataset:\n"
)

cat(
  "Cells:",
  nrow(df_expr),
  "\n"
)

cat(
  "Gene features:",
  ncol(df_expr) - 3,
  "\n"
)

cat(
  "LTS (label = 0):",
  sum(
    df_expr$label == 0
  ),
  "\n"
)

cat(
  "HTS (label = 1):",
  sum(
    df_expr$label == 1
  ),
  "\n"
)

cat(
  "Positive features:",
  sum(
    feature_info$direction == "Positive"
  ),
  "\n"
)

cat(
  "Negative features:",
  sum(
    feature_info$direction == "Negative"
  ),
  "\n"
)


# ==============================================================================
# 9. Export classification / machine-learning input
# ==============================================================================

write.csv(
  df_expr,
  OUTPUT_EXPRESSION_FILE,
  quote = FALSE,
  row.names = FALSE
)

write.csv(
  feature_info,
  OUTPUT_GENE_INFO_FILE,
  quote = FALSE,
  row.names = FALSE
)

write.csv(
  data.frame(
    direction = "Positive",
    gene = genes_pos_matched,
    stringsAsFactors = FALSE
  ),
  OUTPUT_POSITIVE_FILE,
  row.names = FALSE
)

write.csv(
  data.frame(
    direction = "Negative",
    gene = genes_neg_matched,
    stringsAsFactors = FALSE
  ),
  OUTPUT_NEGATIVE_FILE,
  row.names = FALSE
)

missing_gene_info <- rbind(
  data.frame(
    direction = "Positive",
    gene = genes_pos_missing,
    stringsAsFactors = FALSE
  ),
  data.frame(
    direction = "Negative",
    gene = genes_neg_missing,
    stringsAsFactors = FALSE
  )
)

write.csv(
  missing_gene_info,
  OUTPUT_MISSING_FILE,
  row.names = FALSE
)


# ==============================================================================
# 10. Reproducibility information
# ==============================================================================

capture.output(
  sessionInfo(),
  file = "HTS_vs_LTS_Figure1_gene_expression_sessionInfo.txt"
)

message(
  "HTS vs LTS Figure 1 gene-expression input completed successfully."
)
